name: close-pull-request

on:
  pull_request_target:
    types: [ labeled, unlabeled, opened, edited, reopened, synchronize, converted_to_draft, ready_for_review, review_requested ]

jobs:
  close-pull-request:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'size/XL') || contains( github.event.pull_request.labels.*.name, 'size/XXL') }}
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "We can not accept PRs because of PR size over than 'Large(499 line)'"
